input <- "GCCTTACTTCAAAGACCCGATCGAATCAAAGTAGAGTATTGGGCAGCCAGAAAATTCCGTTAAACCACAGTAATTAGCTGCCAGCTGAACGCGTCCTAAAGAGGGGGATGGTAGGCTGCCTTCGTTTCCGCTCAATGTCCAGTGGATGTTCCTCAGGAAAGCTGGCTCTTAGTTGGAGTATGGAATTAGAGACGGAGGATGCCAAGCATCAGTTAATATATGAGCGTGGTCGATGGTTCGTTCGTCGGACTATTATCTTTGGGGACATTTCTGTTACCCTGGCTATCATCGGTGCCCGCAGCCCTCACGGTGATATACACACTTGACCATATAAAGCCCCTCCGATCATGAAGCGGGATTGCGGTAGCACGGCAAACAGAATGTTCCTATGGAACAAATGAGATAAACAGACCGGGTGATTGATGCAATAAGGCGGCCGCAGCTAAATTCGAAGCATGCCAAGCTACTTTGGTTCATCATGATGGTCATTGTGCGTGGGCCGATGTTGAACACTGGATCGCCAAGACAGCCGCCCAGAAGCAAGGAGATTGGTTGGCAGGGTTCTAGTGTTTACCACATAGATGAATGTTAACCACCGGGATCTACCGACGGTCGGCTAAAAACCAGGTCTAGGAAGTCGGACGGTGTGCTCTGCATAACGACGAACTTTGGGAAGGTTGCTCGTTATTGCCTACATCGCTTTTTAAATATAATCTACGGGAAAGGTGCGTAAGCTGATATAAATGGCGAAACTATGCAGATTGCTATACTGGAGCTCTATTGACGTGCTGAATATGTAACAGTGGTGAAATACCGCAGCTTATATGTTATGATCTTTGCAAGTCCGTTCCTCTCGGTACCAGAAAGTATATGTCCCGTG
"
str_spt <- strsplit(input, "")[[1]]

w <- 0
x <- 0
y <- 0
z <- 0

for (char in str_spt) {
 if (char == "A") {
    w <- w + 1
    } else if (char == "C") {
       x <- x + 1
    } else if (char == "G") {
       y <- y + 1
    } else if (char == "T") {
       z <- z + 1
    }
}

cat(w, x, y, z)