library(tictoc)

trans_ratio <- function(dna1, dna2){
    if (length(dna1) != length(dna2)){
        return("Invalid")
    }else{
    dna1_split <- strsplit(dna1, "")[[1]]
    dna2_split <- strsplit(dna2, "")[[1]]
    hamm_dist <- 0
    transversion <- 0
    transition <- 0

    for(i in 1: length(dna1_split)){
        if(dna1_split[i] != dna2_split[i]){
            hamm_dist <- hamm_dist + 1
            if ((dna1_split[i] %in% c("A", "G") && dna2_split[i] %in% c("A", "G")) || 
            (dna1_split[i] %in% c("C", "T") && dna2_split[i] %in% c("C", "T"))) {
                transition <- transition + 1
            }
        }
    }
    transversion <- hamm_dist - transition
    cat("Hamming dist: ", hamm_dist, "\n")
    cat("Transition: ", transition, "\nTransversion:",  transversion, "\n")

    return(transition/transversion)
    }
}

tic()
str1 <- "GAATACGGGTCTGGACGGTGCACCGCTTTGTGAATGTGAACATCGTCTTGTAGAGATATTATATGTAGCGACCGAGCAGCGCAGGAAACCACGACGTGATGCGAACGGTTACCTCTTTTAGGCAATGGTGAGACTTAATATCTCGTCATCTGACAGGCGCTTTATTGTCCCGCTGCCACAGGTAAGTATTTACTTCGCATCTTGGCGTAGGGTCCAGATTTGAGGCATACACTATAAAGATGGCACGTCAAAGGAATCAGAGATGAGTAGCGAGTGGCCGCGATACGAGGGTTGGCCCCAATGGTTGGGTTTCCTTTTGCTTACTCCCCTACACCGCCTATATCTGCATCACCTTTAGGGCACTACTTAAACTTTAGGTATCGGCATAAGCGTGGAGTGAGGTTCTCAAACGTAGTGCCAGTAGGAAAACTGTCTCACGTGGCTAGTTCCACCTGCCAGTCTGTCTAACGCGCGAGTGGTATCTGAGCTTGTGAATAACGTCGATCTATTCTTAACATAAAATTATCACTCTCCACCTAAGGACGGGCAGGTACGATCCTACCGCGACACCGGGCACACAACCAAAGCACATCTGATGCGACCCGGGTTCATGATTCCTGTTTGGGGATCATGGTGATCCCTGTCTGCAGAAATACTTGCGAAACTCGTGTAGCCTTATCGGGGCAGTATCGCTCCACTCAACTCGGCCCGAAAGCTGTCGGCACATTAAACACAGGGCCATCAAACATATTGTGAGCCTTCCCTAAGTGAGTATCCACCAATGCCTCGAATCCAGGACCGGTGTCGCTTGTAACGCGCCTCGATTATATGTTTCCATGATGTGGATATGCATTACGAGCCAGTCCAAGACGCCGTAAGA"
str2 <- "GATTCCAAATCTCGATAACGCATCACGTTATATACGTGAACATCACCTTGCGGAGTCGATATGTGTAGCGTCAGAGCCGCGCGATGAACCATGAATCGGTACCAATGATTACCTCTTCTAGACACTTGTAAAGCTTGACACCTTGTCACCAGATAGATGCACTATTGTTCCGTCGTCACGGGTAAGTTTCTACCTCGCATCCTGGCGTTTGGTTCAAATCTAAAGTATACACTGTAAGGATGGAACGTTGGAGTGATTGCGCATGATGAGCGAGCGACCGGAGTAAGAGGATCGGCCCCGGTGGTTGCACCCCCGTTTGCTTAGCACTCAACATCTTCCATATTCGCGTCACATTTAGGGCTCTAATTAAGGTTTGAGCATCGGAATAGGTATGGGAAAAGTTCCTCAATCGCAGTGTCAGTATGGGAACCGTTTCACGTGGCAACTTCCACCTGCAAGCCTGTCTAACGCGCGAGTTGTATTTGGGCCCGCGCACAACCTTGATTCATCCTGGCCATCGAACGTTCATCCTCTTCCCAGGGACAGGTAGGTGCAGTCCTATGTCGCTGGCAGGCACATGACCAAAACGTATCTGGCGCGCCCCGGGGTCGCAATCAATGTCTAGGGATCATGGTATTCCCTGTCTGCAGAAGCATATGCAAAGCCCACGTAACTATATTAAGGCGCTATCACTCCGCTCCACTTGGCCCTTGAGCTGCTGGTGTGCCAGACACGGGGTCCTCAATTATACGCAAACCCTAACTTAAACAAGTACTCACTAACGCCTCGCATCTACGATCGGCGTCGTTTGTGTTGAGTCTGGAGTACTCTTTTCTATAGCATAACTATGAATCGGGAGTCAGTCCAGGATACCGTAAAA"
cat("Transition/transversion: \n", trans_ratio(str1, str2), "\n")
toc()