library(stringr)

find_motif <- function(seq, sub)
{
    seq_len <- str_length(seq)
    sub_len <- str_length(sub)
    motif <- c()

    for (i in 1:seq_len){
        box <- substring(seq, i, i + sub_len - 1)
        #print(box)

        if (box == sub){
            motif <- append(motif, i)
        }
        if (str_length(box) < sub_len){
            break
        }
    }
    
    return(print(motif))
}

seq1 <- "GTGTCTTGTTGTGTCTTGCGCGTGTCTTGGTGTCTTAGTGTCTTGTGTCTTGTGTCTTATGTGTCTTGTACAGGGTGTCTTGTGTCTTCCCTGTAGGCCATGTGTCTTTGTGTCTTGTGTCTTTAATACCTGTGTCTTGTGTCTTCCGTGTCTTAAGTGTCTTCCGTGTCTTTGTGTCTTAGTGTCTTGTGTCTTGTGTCTTGTGTCTTGTGTCTTCGTTCATTATAACTGTGTCTTGGTTGTGTCTTCGTGTCTTGTGTCTTCATGTGTCTTCGCGTGTCTTCGCAGTGTCTTGCACTGCGTGTCTTGTGTCTTAGCTAAATGTGTCTTGTGTCTTGGTGTCTTAGTGTCTTAGGGTGTCTTGTGTCTTCCTCGTGTCTTGTGTCTTATGGTGTCTTGAGATAAGTGTCTTGTGTCTTCGATAAGTGTCTTCGTGTCTTGTGTCTTCTGGTGTCTTGTGTCTTGGTGTGTCTTGGTGTCTTAGTGTCTTGTCGTGTCTTCGTGTCTTGTGTCTTTAAGTGTCTTGTCGTGTCTTCGTGTCTTGGTGTCTTCCGGGGGAGTGTCTTAGTGTCTTGTGTCTTAGAGTGTCTTCGTGTCTTTGTGTCTTAAAGTGTCTTGAGTGTCTTGCAGCGTGTCTTGTGTCTTTTGTGTCTTAATCTAGGTGTCTTGTGTCTTCGCTTGTGTCTTCGTCGTGTCTTAAAGGTGTCTTTTGTGTCTTAATGTGTCTTGGTGTCTTGTGTCTTAGTGTCTTTAGCGTGTCTTGTTGTGTCTTGTGTGTCTTGAGTGTCTTAATATTGTGTCTTCCGGTCGTGTCTTAGTGTGTCTTGGTGTCTTGTGTCTTCGTGTCTTTGCAGTCTGTGTCTTACCGTGTCTTTGCGTGTCTTGTGTCTTACCGTGTCTTTCCGTGTCTTGGATGGTGTCTTGTGTCTTTGTGTCTTCGTGTCTTGGGTGCAAGTGTCTTAGTGTCTT"
sub1 <- "GTGTCTTGT"

find_motif(seq1, sub1)
